### ISSUE TITLE
App crash after trying to cast youtube video

### ISSUE THREAD

**Issue by gajdur** [athombv/com.google.chromecast#16]
App 0.12.1 on Homey 1.0.2 crashing immediately after attempting to cast youtube video:

Stack trace:

TypeError: Cannot read property 'mediaSessionId' of null
at MediaController.sessionRequest (/node_modules/chromecast-api/node_modules/castv2-client/lib/controllers/media.js:88:44)
at MediaController.stop (/node_modules/chromecast-api/node_modules/castv2-client/lib/controllers/media.js:107:8)
at DefaultMediaReceiver.stop (/node_modules/chromecast-api/node_modules/castv2-client/lib/senders/default-media-receiver.js:42:19)
at Device.stop (/node_modules/chromecast-api/lib/Device.js:178:14)
at /drivers/chromecast/driver.js:99:18
at getDevice (/drivers/chromecast/driver.js:158:3)
at Object.exports.(anonymous function) [as stop] (/drivers/chromecast/driver.js:97:3)
at Object.onFlowActionCastVideo (/app.js:28:13)
at emitThree (events.js:97:13)
at Object.emit (events.js:175:7)

Exit code: 1
Exit signal: null

**Comment by BasKiers** [comment]
The app has been rewritten and all crashes should be fixed. Please open a new issue if you experience problems.
